package ray1024.st;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class ChromeLoginLogoutTest extends BaseTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void loginLogout() {
        driver.get("https://www.answers.com/");
        driver.manage().window().setSize(new Dimension(1920, 1048));
        driver.findElement(By.cssSelector(".m-2")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".m-2"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".col-span-6")).click();
        {
            WebElement element = driver.findElement(By.linkText("Animals & Plants"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("email-input")).click();
        driver.findElement(By.id("email-input")).sendKeys("X_ANIME_FUTURE@mail.ru");
        driver.findElement(By.cssSelector(".px-9")).click();
        driver.findElement(By.id("outlined-adornment-password")).click();
        driver.findElement(By.id("outlined-adornment-password")).sendKeys("X_ANIME_FUTURE");
        driver.findElement(By.cssSelector(".false")).click();
    }
}
