package ray1024.st;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class ChromeFindAnAnswerTest extends BaseTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void findAnAnswer() {
        driver.get("https://www.answers.com/");
        driver.manage().window().setSize(new Dimension(1920, 1048));
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section/div[2]/div/div/input")).click();
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section/div[2]/div/div/input")).sendKeys("What if");
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section/div[2]/button/img")).click();
    }
}
