package ray1024.st;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class FirefoxMainPageTest extends BaseTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void mainPage() {
        driver.get("https://www.answers.com/");
        driver.manage().window().setSize(new Dimension(1920, 1048));
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section")).click();
        assertThat(driver.findElement(By.xpath("//h1[contains(.,\'What is your question?\')]")).getText(), is("What is your question?"));
        driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/main/section/span/span")).getText(), is("or"));
        driver.findElement(By.xpath("//h2[contains(.,\'Browse Subjects\')]")).click();
        assertThat(driver.findElement(By.xpath("//h2[contains(.,\'Browse Subjects\')]")).getText(), is("Browse Subjects"));
        driver.findElement(By.xpath("//h2[contains(.,\'Browse Categories\')]")).click();
        assertThat(driver.findElement(By.xpath("//h2[contains(.,\'Browse Categories\')]")).getText(), is("Browse Categories"));
        driver.findElement(By.xpath("//div[@id=\'site-container\']/section/div/div")).click();
        assertThat(driver.findElement(By.xpath("//div/section/div/div")).getText(), is("Trending Questions"));
        driver.findElement(By.xpath("//div[@id=\'answ-footer\']/div")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'answ-footer\']/div/div[3]")).getText(), is("Copyright ©2024 Infospace Holdings LLC, A System1 Company. All Rights Reserved. The material on this site can not be reproduced, distributed, transmitted, cached or otherwise used, except with prior written permission of Answers."));
    }
}
